### ISSUE TITLE
Harmony included now with VRCSDK Base 3.4.0

### ISSUE THREAD

**Issue by babo4d** [rrazgriz/RATS#25]
Causes errors when RATS also tried to load Harmony.

**Comment by Rivera-IV** [comment]
![image](https://github.com/rrazgriz/RATS/assets/89464945/b2bb0c2e-2198-4a2b-aac0-92d44f4760c5)

Yeah new SDK version has its own 0harmony.dll now which prevents uploading in the SDK due to errors.
Removing the one included with RATS fixes it.

**Comment by rrazgriz** [comment]
Thanks for the notification. This is part of why I made Harmony a separate package (along with other packages including it). 

You can fix this by removing the Harmony package in VCC/vpm, or the dll if you have harmony from a different source. RATS itself is standalone.

![image](https://github.com/rrazgriz/RATS/assets/47901762/b986b441-8a50-4eed-8893-80d1dc6cdae5)

Unfortunately, since (as far as I'm aware) there's no way to declare incompatibilities with VPM, I don't think I can update the Harmony package to mitigate this in a meaningful way. As a result, I'll be removing it from my listing in the near future, and recommending people use SDK 3.4.0 or higher.

**Comment by rrazgriz** [comment]
I've released RATS 1.1.4. Updating to this version now requires the Base SDK (3.4.0 or higher), and marks `one.razgriz.harmony-vpm` as a legacy package, which will remove it when using VCC 2.1.4 or higher. I think this addresses the issue adequately. 

![image](https://github.com/rrazgriz/RATS/assets/47901762/9acfab40-7cf1-4f7d-b4a0-204c12672eff)
