### ISSUE TITLE
Match Custom node Style size to default size

### ISSUE THREAD

**Issue by TayouVR** [rrazgriz/RATS#4]
Currently the custom node style is slightly larger than the default style meaning the nodes don't look properly snapped when using grid snapping.
Comparisons:

| Default         | Custom    |
|--------------|-----------|
| ![image](https://user-images.githubusercontent.com/31988415/229621481-2d436d07-2971-4561-b4a9-322862cf567d.png)|![image](https://user-images.githubusercontent.com/31988415/229621509-75634857-b83a-44d9-92a6-e4a9ca4c2c9f.png)      | 
| ![image](https://user-images.githubusercontent.com/31988415/229622506-4b5fc177-12ff-497c-9ff7-585a2e593805.png)| ![image](https://user-images.githubusercontent.com/31988415/229622652-e5eeecc2-7492-4b2c-a5d6-f19a6c4f588d.png) | 
|![image](https://user-images.githubusercontent.com/31988415/229622781-30387fe4-625e-4995-b487-cd4c1f8f2e52.png) | ![image](https://user-images.githubusercontent.com/31988415/229622833-2a0297b7-3cd8-48ab-96e4-724be8621af2.png) | 
|![image](https://user-images.githubusercontent.com/31988415/229622902-70c3c188-1593-45ec-95bb-3fa1c4985768.png) | ![image](https://user-images.githubusercontent.com/31988415/229622946-f07dd9bc-6b07-4f88-a311-e54c0067c822.png) | 

I tried modifying the PSD myself, but I think gimp is not having a great time there, and i don't have or want to use photoshop.

I do generally prefer the flat style of the custom nodes, but them being too big triggers my OCD.. >.<

**Comment by rrazgriz** [comment]
Addressed this in 1.1.0. Ideally I'd like to generate the textures from code at runtime, instead of having to do fiddly image editing, but this'll do for now.

Old:
![Unity_hvndZesLFQ](https://user-images.githubusercontent.com/47901762/230744664-58920e7d-f322-44e6-bf23-b9392a50e8b1.png)

New:
![Unity_yuvOIBqRJ0](https://user-images.githubusercontent.com/47901762/230744666-0917a50b-d000-49ed-bdf5-6ae301dba3a5.png)
